spring.application.name=reserbayan

#DB connection
spring.datasource.url=jdbc:mysql://localhost:3306/reserbayan
spring.datasource.username=root
spring.datasource.password=Cutesikokoi123?

#JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect